name = "mlwk-global-site"
compatibility_date = "2026-07-01"
pages_build_output_dir = "dist"

# [[r2_buckets]]   TODO: uncomment after creating mlwk-inquiry-files bucket
# binding = "INQUIRY_FILES"
# bucket_name = "mlwk-inquiry-files"

[[d1_databases]]
binding = "DB"
database_name = "mlwk-inquiries"
database_id = "04808c9a-46d9-4a38-9c7d-962349d5efdf"
