import type { Locale } from "../content";

export const storeCopy = {
  en: {
    shop: "Shop",
    shopTitle: "Considered objects for every interior",
    shopIntro: "Hardware, furniture, textiles and home objects — each piece selected for the same material discipline that guides our project work.",
    preview: "Preview catalogue · Sandbox checkout",
    search: "Search products",
    all: "All",
    sort: "Sort",
    featured: "Featured",
    priceLow: "Price: low to high",
    priceHigh: "Price: high to low",
    add: "Add to cart",
    added: "Added",
    details: "View details",
    finish: "Finish",
    quantity: "Quantity",
    specifications: "Specifications",
    cart: "Cart",
    emptyCart: "Your cart is quietly waiting.",
    continueShopping: "Continue shopping",
    subtotal: "Subtotal",
    shipping: "Shipping",
    total: "Total",
    checkout: "Checkout",
    duties: "Import duties and local taxes are not included.",
    remove: "Remove",
    account: "Account",
    signIn: "Sign in",
    loginIntro: "Keep orders, delivery details and considered pieces together in one private place.",
    signOut: "Sign out",
    backToSite: "Back to website",
    loginSlides: [
      "Precision, from drawing to finish.",
      "Surfaces that define a room.",
      "Every detail, made to belong.",
    ],
    createAccount: "Create an account",
    welcomeBack: "Welcome back",
    haveAccount: "Already have an account?",
    noAccount: "Don't have an account?",
    logIn: "Log in",
    signUp: "Sign up",
    firstName: "First name",
    lastName: "Last name",
    password: "Enter your password",
    agreeTerms: "I agree to the",
    termsOfService: "Terms of Service",
    privacyPolicy: "Privacy Policy",
    and: "and",
    signUpButton: "Create account",
    signInButton: "Sign in",
    orContinue: "Or continue with",
    google: "Continue with Google",
    x: "Continue with X",
    email: "Email address",
    sendCode: "Send six-digit code",
    code: "Verification code",
    verify: "Verify and continue",
    authPreview: "Connect Supabase credentials to enable live sign-in.",
    orderHistory: "Orders",
    addresses: "Addresses",
    favorites: "Favourites",
    noOrders: "No orders yet.",
    noAddresses: "No saved addresses.",
    noFavorites: "No saved favourites.",
    saveAddress: "Save address",
    checkoutTitle: "Complete your order",
    contact: "Contact",
    delivery: "Delivery address",
    payment: "Secure sandbox payment",
    payPalNote: "PayPal Sandbox will open below. No real money will be charged.",
    placeDemo: "Create preview order",
    configuration: "Payment credentials are not configured. A preview order can still be created locally.",
    confirmationTitle: "Your order is confirmed",
    confirmationText: "A sandbox order has been recorded. No real payment has been taken.",
    claim: "Save this order to your account",
    backToShop: "Back to shop",
    category: {
      pulls: "Pulls",
      hardware: "Hardware",
      wardrobe: "Wardrobe",
      interiors: "Interior fittings",
      lighting: "Lighting",
      samples: "Samples",
      furniture: "Furniture",
      textiles: "Textiles",
      decor: "Objects",
    },
  },
  zh: {
    shop: "标品商城",
    shopTitle: "为空间精选的每一件物品",
    shopIntro: "五金、成品家具、织物与家居摆件，每件都以 MLWK 木作项目一贯的材质标准为选择依据。",
    preview: "演示商品 · Sandbox 测试结账",
    search: "搜索商品",
    all: "全部",
    sort: "排序",
    featured: "精选排序",
    priceLow: "价格从低到高",
    priceHigh: "价格从高到低",
    add: "加入购物车",
    added: "已加入",
    details: "查看详情",
    finish: "饰面",
    quantity: "数量",
    specifications: "规格",
    cart: "购物车",
    emptyCart: "购物车还在安静地等待。",
    continueShopping: "继续选购",
    subtotal: "商品小计",
    shipping: "跨境运费",
    total: "合计",
    checkout: "进入结账",
    duties: "价格不包含目的地进口税费与当地税费。",
    remove: "移除",
    account: "账户中心",
    signIn: "登录",
    loginIntro: "在一处私密空间中，管理订单、收货信息与为项目收藏的物件。",
    signOut: "退出登录",
    backToSite: "返回网站",
    loginSlides: [
      "从图纸到成品，精确如一。",
      "墙面，定义一个空间的气质。",
      "每一个细节，都该属于这里。",
    ],
    createAccount: "创建账户",
    welcomeBack: "欢迎回来",
    haveAccount: "已有账户？",
    noAccount: "还没有账户？",
    logIn: "登录",
    signUp: "注册",
    firstName: "名字",
    lastName: "姓氏",
    password: "输入密码",
    agreeTerms: "我已阅读并同意",
    termsOfService: "服务条款",
    privacyPolicy: "隐私政策",
    and: "和",
    signUpButton: "创建账户",
    signInButton: "登录",
    orContinue: "或使用以下方式继续",
    google: "使用 Google 继续",
    x: "使用 X 继续",
    email: "邮箱地址",
    sendCode: "发送六位验证码",
    code: "邮箱验证码",
    verify: "验证并继续",
    authPreview: "配置 Supabase 后即可启用真实登录。",
    orderHistory: "我的订单",
    addresses: "收货地址",
    favorites: "收藏商品",
    noOrders: "还没有订单。",
    noAddresses: "还没有保存地址。",
    noFavorites: "还没有收藏商品。",
    saveAddress: "保存地址",
    checkoutTitle: "完成订单",
    contact: "联系信息",
    delivery: "收货地址",
    payment: "安全测试支付",
    payPalNote: "下方将使用 PayPal Sandbox，不会产生真实扣款。",
    placeDemo: "创建演示订单",
    configuration: "尚未配置支付密钥，仍可在本地建立预览订单。",
    confirmationTitle: "订单已经确认",
    confirmationText: "Sandbox 演示订单已记录，没有产生真实扣款。",
    claim: "将订单保存到账户",
    backToShop: "返回商城",
    category: {
      pulls: "拉手",
      hardware: "五金",
      wardrobe: "衣柜配件",
      interiors: "内部收纳",
      lighting: "灯光",
      samples: "样品",
      furniture: "成品家具",
      textiles: "软装织物",
      decor: "摆件",
    },
  },
  ar: {
    shop: "المتجر",
    shopTitle: "قطع لمساحات مدروسة",
    shopIntro: "كتالوج تجريبي من المقابض والتجهيزات والإكسسوارات الداخلية بنفس عناية مشاريع MLWK.",
    preview: "كتالوج تجريبي · دفع Sandbox",
    search: "بحث عن المنتجات",
    all: "الكل",
    sort: "الترتيب",
    featured: "مختارة",
    priceLow: "السعر: من الأقل",
    priceHigh: "السعر: من الأعلى",
    add: "أضف إلى السلة",
    added: "تمت الإضافة",
    details: "عرض التفاصيل",
    finish: "التشطيب",
    quantity: "الكمية",
    specifications: "المواصفات",
    cart: "السلة",
    emptyCart: "سلة التسوق بانتظارك.",
    continueShopping: "متابعة التسوق",
    subtotal: "المجموع الفرعي",
    shipping: "الشحن",
    total: "الإجمالي",
    checkout: "إتمام الشراء",
    duties: "لا تشمل الأسعار رسوم الاستيراد والضرائب المحلية.",
    remove: "إزالة",
    account: "الحساب",
    signIn: "تسجيل الدخول",
    loginIntro: "احتفظ بالطلبات وتفاصيل التوصيل والقطع المختارة في مساحة خاصة واحدة.",
    signOut: "تسجيل الخروج",
    backToSite: "العودة للموقع",
    loginSlides: [
      "الدقة، من الرسم إلى التشطيب.",
      "الأسطح التي تحدد طابع الغرفة.",
      "كل تفصيل، صُنع لينتمي.",
    ],
    createAccount: "إنشاء حساب",
    welcomeBack: "مرحباً بعودتك",
    haveAccount: "هل لديك حساب؟",
    noAccount: "ليس لديك حساب؟",
    logIn: "تسجيل الدخول",
    signUp: "إنشاء حساب",
    firstName: "الاسم الأول",
    lastName: "اسم العائلة",
    password: "أدخل كلمة المرور",
    agreeTerms: "أوافق على",
    termsOfService: "شروط الخدمة",
    privacyPolicy: "سياسة الخصوصية",
    and: "و",
    signUpButton: "إنشاء حساب",
    signInButton: "تسجيل الدخول",
    orContinue: "أو تابع باستخدام",
    google: "المتابعة عبر Google",
    x: "المتابعة عبر X",
    email: "البريد الإلكتروني",
    sendCode: "إرسال رمز من ستة أرقام",
    code: "رمز التحقق",
    verify: "تحقق وتابع",
    authPreview: "أضف بيانات Supabase لتفعيل تسجيل الدخول.",
    orderHistory: "الطلبات",
    addresses: "العناوين",
    favorites: "المفضلة",
    noOrders: "لا توجد طلبات بعد.",
    noAddresses: "لا توجد عناوين محفوظة.",
    noFavorites: "لا توجد منتجات مفضلة.",
    saveAddress: "حفظ العنوان",
    checkoutTitle: "أكمل طلبك",
    contact: "بيانات التواصل",
    delivery: "عنوان التوصيل",
    payment: "دفع تجريبي آمن",
    payPalNote: "سيتم استخدام PayPal Sandbox ولن يتم خصم أموال حقيقية.",
    placeDemo: "إنشاء طلب تجريبي",
    configuration: "بيانات الدفع غير مهيأة. يمكن إنشاء طلب معاينة محلياً.",
    confirmationTitle: "تم تأكيد طلبك",
    confirmationText: "تم تسجيل طلب Sandbox دون أي خصم حقيقي.",
    claim: "حفظ الطلب في حسابك",
    backToShop: "العودة إلى المتجر",
    category: {
      pulls: "مقابض",
      hardware: "حديد وتجهيزات",
      wardrobe: "خزائن",
      interiors: "تجهيزات داخلية",
      lighting: "إضاءة",
      samples: "عينات",
      furniture: "أثاث",
      textiles: "منسوجات",
      decor: "ديكور",
    },
  },
  de: {
    shop: "Shop",
    shopTitle: "Durchdachte Objekte für jeden Raum",
    shopIntro: "Beschläge, Möbel, Textilien und Wohnobjekte — jedes Stück nach denselben Maßstäben wie unsere Projekte ausgewählt.",
    preview: "Vorschaukatalog · Sandbox-Checkout",
    search: "Produkte suchen",
    all: "Alle",
    sort: "Sortieren",
    featured: "Ausgewählt",
    priceLow: "Preis aufsteigend",
    priceHigh: "Preis absteigend",
    add: "In den Warenkorb",
    added: "Hinzugefügt",
    details: "Details ansehen",
    finish: "Oberfläche",
    quantity: "Menge",
    specifications: "Spezifikationen",
    cart: "Warenkorb",
    emptyCart: "Ihr Warenkorb wartet noch.",
    continueShopping: "Weiter einkaufen",
    subtotal: "Zwischensumme",
    shipping: "Versand",
    total: "Gesamt",
    checkout: "Zur Kasse",
    duties: "Einfuhrabgaben und lokale Steuern sind nicht enthalten.",
    remove: "Entfernen",
    account: "Konto",
    signIn: "Anmelden",
    loginIntro: "Bestellungen, Lieferdetails und ausgewählte Stücke an einem privaten Ort verwalten.",
    signOut: "Abmelden",
    backToSite: "Zurück zur Website",
    loginSlides: [
      "Präzision, von der Zeichnung bis zur Ausführung.",
      "Oberflächen, die einen Raum definieren.",
      "Jedes Detail, gemacht um dazuzugehören.",
    ],
    createAccount: "Konto erstellen",
    welcomeBack: "Willkommen zurück",
    haveAccount: "Haben Sie bereits ein Konto?",
    noAccount: "Noch kein Konto?",
    logIn: "Anmelden",
    signUp: "Registrieren",
    firstName: "Vorname",
    lastName: "Nachname",
    password: "Passwort eingeben",
    agreeTerms: "Ich stimme den",
    termsOfService: "Nutzungsbedingungen",
    privacyPolicy: "Datenschutzerklärung",
    and: "und",
    signUpButton: "Konto erstellen",
    signInButton: "Anmelden",
    orContinue: "Oder fortfahren mit",
    google: "Mit Google fortfahren",
    x: "Mit X fortfahren",
    email: "E-Mail-Adresse",
    sendCode: "Sechsstelligen Code senden",
    code: "Bestätigungscode",
    verify: "Prüfen und fortfahren",
    authPreview: "Supabase-Zugangsdaten aktivieren die Anmeldung.",
    orderHistory: "Bestellungen",
    addresses: "Adressen",
    favorites: "Favoriten",
    noOrders: "Noch keine Bestellungen.",
    noAddresses: "Keine gespeicherten Adressen.",
    noFavorites: "Keine gespeicherten Favoriten.",
    saveAddress: "Adresse speichern",
    checkoutTitle: "Bestellung abschließen",
    contact: "Kontakt",
    delivery: "Lieferadresse",
    payment: "Sichere Sandbox-Zahlung",
    payPalNote: "PayPal Sandbox belastet kein echtes Geld.",
    placeDemo: "Vorschaubestellung erstellen",
    configuration: "Zahlungsdaten fehlen. Eine lokale Vorschau ist weiterhin möglich.",
    confirmationTitle: "Bestellung bestätigt",
    confirmationText: "Die Sandbox-Bestellung wurde ohne echte Zahlung erfasst.",
    claim: "Bestellung im Konto speichern",
    backToShop: "Zurück zum Shop",
    category: {
      pulls: "Griffe",
      hardware: "Beschläge",
      wardrobe: "Ankleide",
      interiors: "Innenausstattung",
      lighting: "Licht",
      samples: "Muster",
      furniture: "Möbel",
      textiles: "Textilien",
      decor: "Objekte",
    },
  },
  fr: {
    shop: "Boutique",
    shopTitle: "Des objets considérés pour chaque intérieur",
    shopIntro: "Quincaillerie, mobilier, textiles et objets — chaque pièce sélectionnée avec la même exigence que nos projets.",
    preview: "Catalogue d'aperçu · Paiement Sandbox",
    search: "Rechercher",
    all: "Tout",
    sort: "Trier",
    featured: "Sélection",
    priceLow: "Prix croissant",
    priceHigh: "Prix décroissant",
    add: "Ajouter au panier",
    added: "Ajouté",
    details: "Voir le détail",
    finish: "Finition",
    quantity: "Quantité",
    specifications: "Caractéristiques",
    cart: "Panier",
    emptyCart: "Votre panier vous attend.",
    continueShopping: "Continuer",
    subtotal: "Sous-total",
    shipping: "Livraison",
    total: "Total",
    checkout: "Commander",
    duties: "Les droits d'importation et taxes locales ne sont pas inclus.",
    remove: "Retirer",
    account: "Compte",
    signIn: "Connexion",
    loginIntro: "Réunissez commandes, adresses de livraison et pièces sélectionnées dans un espace privé.",
    signOut: "Déconnexion",
    backToSite: "Retour au site",
    loginSlides: [
      "Précision, du dessin à la finition.",
      "Des surfaces qui définissent une pièce.",
      "Chaque détail, fait pour appartenir.",
    ],
    createAccount: "Créer un compte",
    welcomeBack: "Bon retour",
    haveAccount: "Vous avez déjà un compte ?",
    noAccount: "Pas encore de compte ?",
    logIn: "Se connecter",
    signUp: "S'inscrire",
    firstName: "Prénom",
    lastName: "Nom",
    password: "Entrez votre mot de passe",
    agreeTerms: "J'accepte les",
    termsOfService: "Conditions d'utilisation",
    privacyPolicy: "Politique de confidentialité",
    and: "et",
    signUpButton: "Créer un compte",
    signInButton: "Se connecter",
    orContinue: "Ou continuer avec",
    google: "Continuer avec Google",
    x: "Continuer avec X",
    email: "Adresse e-mail",
    sendCode: "Envoyer le code à six chiffres",
    code: "Code de vérification",
    verify: "Vérifier et continuer",
    authPreview: "Configurez Supabase pour activer la connexion.",
    orderHistory: "Commandes",
    addresses: "Adresses",
    favorites: "Favoris",
    noOrders: "Aucune commande.",
    noAddresses: "Aucune adresse enregistrée.",
    noFavorites: "Aucun favori.",
    saveAddress: "Enregistrer l'adresse",
    checkoutTitle: "Finaliser la commande",
    contact: "Contact",
    delivery: "Adresse de livraison",
    payment: "Paiement Sandbox sécurisé",
    payPalNote: "PayPal Sandbox ne débitera aucun argent réel.",
    placeDemo: "Créer une commande d'aperçu",
    configuration: "Le paiement n'est pas configuré. Une commande locale reste possible.",
    confirmationTitle: "Commande confirmée",
    confirmationText: "La commande Sandbox est enregistrée sans paiement réel.",
    claim: "Enregistrer dans votre compte",
    backToShop: "Retour à la boutique",
    category: {
      pulls: "Poignées",
      hardware: "Quincaillerie",
      wardrobe: "Dressing",
      interiors: "Aménagements",
      lighting: "Éclairage",
      samples: "Échantillons",
      furniture: "Mobilier",
      textiles: "Textiles",
      decor: "Objets",
    },
  },
} satisfies Record<Locale, Record<string, unknown>>;

export function getStoreCopy(locale: Locale) {
  return storeCopy[locale] as typeof storeCopy.en;
}
