export const locales = ["en", "ar", "zh", "de", "fr"] as const;
export type Locale = (typeof locales)[number];

export const localeMeta: Record<
  Locale,
  { label: string; short: string; dir: "ltr" | "rtl" }
> = {
  en: { label: "English", short: "EN", dir: "ltr" },
  ar: { label: "العربية", short: "AR", dir: "rtl" },
  zh: { label: "中文", short: "中", dir: "ltr" },
  de: { label: "Deutsch", short: "DE", dir: "ltr" },
  fr: { label: "Français", short: "FR", dir: "ltr" },
};

export type CollectionItem = {
  slug: string;
  image: string;
  name: Record<Locale, string>;
  description: Record<Locale, string>;
  features: Record<Locale, string[]>;
};

export const collections: CollectionItem[] = [
  {
    slug: "kitchens",
    image: "/media/kitchens.png",
    name: {
      en: "Kitchens",
      ar: "المطابخ",
      zh: "定制厨房",
      de: "Küchen",
      fr: "Cuisines",
    },
    description: {
      en: "Integrated cabinetry engineered around appliances, services and the way a project is built.",
      ar: "خزائن متكاملة مصممة حول الأجهزة والخدمات وطريقة تنفيذ المشروع.",
      zh: "围绕电器、设备接口与项目施工方式进行深化的整体柜体系统。",
      de: "Integrierte Schranklösungen, abgestimmt auf Geräte, Haustechnik und Bauweise.",
      fr: "Des agencements intégrés conçus autour des appareils, des réseaux et du mode de construction.",
    },
    features: {
      en: ["Full-height storage", "Integrated appliances", "Matched veneers", "Custom internals"],
      ar: ["تخزين كامل الارتفاع", "أجهزة مدمجة", "قشرة خشبية متطابقة", "تجهيزات داخلية مخصصة"],
      zh: ["通顶收纳", "嵌入式电器", "木皮对纹", "定制内部五金"],
      de: ["Raumhoher Stauraum", "Integrierte Geräte", "Furnierabwicklung", "Individueller Innenausbau"],
      fr: ["Rangements toute hauteur", "Appareils intégrés", "Placage raccordé", "Aménagement intérieur sur mesure"],
    },
  },
  {
    slug: "wardrobes",
    image: "/media/wardrobes.png",
    name: {
      en: "Wardrobes",
      ar: "خزائن الملابس",
      zh: "衣柜系统",
      de: "Kleiderschränke",
      fr: "Dressings",
    },
    description: {
      en: "Dressing systems that align storage, lighting and architecture in one continuous interior.",
      ar: "أنظمة ملابس تجمع التخزين والإضاءة والعمارة في مساحة داخلية واحدة متكاملة.",
      zh: "将收纳、灯光与建筑界面整合为连续空间的衣柜系统。",
      de: "Ankleidesysteme, die Stauraum, Licht und Architektur zu einem Interieur verbinden.",
      fr: "Des dressings qui réunissent rangement, éclairage et architecture dans un ensemble continu.",
    },
    features: {
      en: ["Hinged or sliding", "Glass framing", "Integrated lighting", "Accessory systems"],
      ar: ["مفصلي أو منزلق", "إطارات زجاجية", "إضاءة مدمجة", "أنظمة إكسسوارات"],
      zh: ["平开或移门", "玻璃框架", "集成照明", "配件系统"],
      de: ["Dreh- oder Schiebetüren", "Glasrahmen", "Integriertes Licht", "Zubehörsysteme"],
      fr: ["Battant ou coulissant", "Cadres vitrés", "Éclairage intégré", "Accessoires intérieurs"],
    },
  },
  {
    slug: "vanities",
    image: "/media/vanities.png",
    name: {
      en: "Vanities",
      ar: "وحدات الحمام",
      zh: "浴室柜",
      de: "Waschtische",
      fr: "Meubles vasques",
    },
    description: {
      en: "Moisture-aware vanity systems coordinated with stone, mirrors, lighting and plumbing.",
      ar: "وحدات حمام تراعي الرطوبة وتنسق مع الحجر والمرايا والإضاءة والسباكة.",
      zh: "兼顾防潮性能，并与石材、镜柜、灯光及给排水协调的浴室柜系统。",
      de: "Feuchtraumgerechte Waschtische, abgestimmt auf Stein, Spiegel, Licht und Sanitär.",
      fr: "Des meubles vasques adaptés à l'humidité et coordonnés avec pierre, miroirs, éclairage et plomberie.",
    },
    features: {
      en: ["Moisture-ready cores", "Stone coordination", "Mirror cabinets", "Wall-hung systems"],
      ar: ["ألواح مقاومة للرطوبة", "تنسيق الحجر", "خزائن مرايا", "أنظمة معلقة"],
      zh: ["防潮基材", "石材协调", "镜柜系统", "悬挂式安装"],
      de: ["Feuchtebeständige Kerne", "Steinabstimmung", "Spiegelschränke", "Wandhängende Systeme"],
      fr: ["Panneaux hydrofuges", "Coordination pierre", "Armoires miroirs", "Systèmes suspendus"],
    },
  },
  {
    slug: "wall-panels",
    image: "/media/wall-panels.png",
    name: {
      en: "Wall Panels",
      ar: "كسوات الجدران",
      zh: "墙板系统",
      de: "Wandpaneele",
      fr: "Panneaux muraux",
    },
    description: {
      en: "Panel systems that carry veneer matching, concealed access and room-scale detailing.",
      ar: "أنظمة كسوة تجمع تطابق القشرة والمداخل المخفية وتفاصيل المقياس المعماري.",
      zh: "实现木皮连续对纹、隐形检修口与建筑尺度细节的墙板系统。",
      de: "Paneelsysteme mit Furnierabwicklung, verdeckten Zugängen und raumbezogenen Details.",
      fr: "Des panneaux avec raccord de placage, accès dissimulés et détails à l'échelle de la pièce.",
    },
    features: {
      en: ["Flat, reeded or shaped", "Concealed access", "Integrated doors", "Acoustic options"],
      ar: ["مسطح أو مخدد أو مشكل", "وصول مخفي", "أبواب مدمجة", "خيارات صوتية"],
      zh: ["平板、格栅或造型", "隐形检修", "门墙一体", "声学选项"],
      de: ["Glatt, geriffelt oder geformt", "Verdeckte Zugänge", "Integrierte Türen", "Akustikoptionen"],
      fr: ["Plat, cannelé ou formé", "Accès dissimulés", "Portes intégrées", "Options acoustiques"],
    },
  },
  {
    slug: "interior-doors",
    image: "/media/interior-doors.png",
    name: {
      en: "Interior Doors",
      ar: "الأبواب الداخلية",
      zh: "室内门",
      de: "Innentüren",
      fr: "Portes intérieures",
    },
    description: {
      en: "Flush, framed and pivot doors developed as part of the surrounding millwork.",
      ar: "أبواب مستوية أو بإطار أو محورية تُطوّر كجزء من أعمال الخشب المحيطة.",
      zh: "与周边木作一体深化的平板门、框架门与中轴门系统。",
      de: "Flächenbündige, gerahmte und Pivot-Türen als Teil des umliegenden Innenausbaus.",
      fr: "Portes affleurantes, encadrées ou pivotantes développées avec les boiseries environnantes.",
    },
    features: {
      en: ["Flush frames", "Pivot systems", "Veneer matching", "Hardware coordination"],
      ar: ["إطارات مستوية", "أنظمة محورية", "تطابق القشرة", "تنسيق الحديد"],
      zh: ["隐形门框", "中轴系统", "木皮对纹", "五金协调"],
      de: ["Bündige Zargen", "Pivot-Systeme", "Furnierabwicklung", "Beschlagkoordination"],
      fr: ["Huisseries affleurantes", "Systèmes pivot", "Raccord de placage", "Coordination quincaillerie"],
    },
  },
  {
    slug: "bespoke-built-ins",
    image: "/media/bespoke-built-ins.png",
    name: {
      en: "Bespoke Built-ins",
      ar: "تجهيزات مدمجة خاصة",
      zh: "异形定制",
      de: "Individuelle Einbauten",
      fr: "Agencements spéciaux",
    },
    description: {
      en: "Libraries, bars, media walls and one-off elements resolved for a specific space.",
      ar: "مكتبات وبارات وجدران وسائط وعناصر خاصة مصممة لمساحة بعينها.",
      zh: "针对特定空间完成深化的书房、吧台、媒体墙及非标木作。",
      de: "Bibliotheken, Bars, Medienwände und Einzelanfertigungen für den jeweiligen Raum.",
      fr: "Bibliothèques, bars, murs média et pièces uniques conçus pour un espace précis.",
    },
    features: {
      en: ["One-off geometry", "Mixed materials", "Integrated services", "Prototype support"],
      ar: ["هندسة خاصة", "مواد مختلطة", "خدمات مدمجة", "دعم النماذج"],
      zh: ["非标造型", "复合材料", "设备集成", "样品验证"],
      de: ["Sondergeometrien", "Materialkombinationen", "Integrierte Technik", "Prototypenservice"],
      fr: ["Géométries uniques", "Matériaux mixtes", "Réseaux intégrés", "Aide au prototypage"],
    },
  },
];

export const solutions = [
  {
    slug: "residential",
    image: "/media/hero-poster.png",
    name: { en: "Luxury Residential", ar: "السكن الفاخر", zh: "高端住宅", de: "Luxuswohnen", fr: "Résidentiel haut de gamme" },
    description: {
      en: "Whole-home packages coordinated room by room, from early design development to labeled installation sets.",
      ar: "حزم متكاملة للمنزل تُنسق غرفة بعد غرفة من تطوير التصميم حتى مجموعات التركيب المرقمة.",
      zh: "从前期深化到编号安装包，按房间协调整套住宅木作。",
      de: "Ganzheitliche Pakete, Raum für Raum koordiniert, von der Planung bis zum beschrifteten Montagesatz.",
      fr: "Des ensembles complets, coordonnés pièce par pièce, de l'étude aux lots de pose repérés.",
    },
  },
  {
    slug: "hospitality",
    image: "/media/wall-panels.png",
    name: { en: "Hospitality", ar: "الضيافة", zh: "酒店与餐饮", de: "Hospitality", fr: "Hôtellerie" },
    description: {
      en: "Repeatable room standards, feature spaces and material control for hotels, clubs and restaurants.",
      ar: "معايير غرف قابلة للتكرار ومساحات مميزة وتحكم بالمواد للفنادق والنوادي والمطاعم.",
      zh: "为酒店、会所及餐饮空间提供可复制的客房标准、重点空间与材料控制。",
      de: "Reproduzierbare Zimmerstandards, besondere Räume und Materialkontrolle für Hotels, Clubs und Restaurants.",
      fr: "Standards de chambres reproductibles, espaces signatures et maîtrise des matériaux pour hôtels, clubs et restaurants.",
    },
  },
  {
    slug: "commercial",
    image: "/media/bespoke-built-ins.png",
    name: { en: "Commercial", ar: "المشاريع التجارية", zh: "商业空间", de: "Gewerbe", fr: "Tertiaire" },
    description: {
      en: "Durable, coordinated millwork for offices, retail and public-facing interiors.",
      ar: "أعمال خشبية متينة ومنسقة للمكاتب والتجزئة والمساحات العامة.",
      zh: "适用于办公、零售及公共空间的耐用型定制木作。",
      de: "Robuster, koordinierter Innenausbau für Büros, Retail und öffentliche Räume.",
      fr: "Des agencements durables et coordonnés pour bureaux, commerces et espaces publics.",
    },
  },
] as const;

export const copy = {
  en: {
    nav: { collections: "Collections", solutions: "Solutions", projects: "Projects", capabilities: "Capabilities", company: "Company", quote: "Send Your Drawings" },
    common: { explore: "Explore", viewAll: "View all", learnMore: "Learn more", concept: "Design direction", back: "Back", openMenu: "Open menu", closeMenu: "Close menu", language: "Language" },
    home: {
      badge: "Millwork, made to belong",
      title: "Made for the rooms people remember",
      intro: "From the first pencil line to the final grain match, MLWK shapes cabinetry and architectural millwork for homes, hotels and spaces meant to endure.",
      proofValue: "500+",
      proofLabel: "Custom interiors shaped by our manufacturing team",
      collectionsEyebrow: "One material language, carried through the room",
      collectionsTitle: "Every room, one continuous voice",
      collectionsText: "Kitchens, wardrobes, doors and panelled walls developed as a single interior — so the grain, tone and proportion carry unbroken through every surface.",
      processEyebrow: "From first line to final room",
      processTitle: "Complex work, resolved with quiet precision",
      processText: "Every drawing, sample and label moves the project forward. Together they turn a singular design into a clear, auditable path from workshop to installed room.",
      directionEyebrow: "Material stories",
      directionTitle: "Not a style catalogue. A language built for your project.",
      directionText: "These concept studies explore atmosphere, proportion and material continuity across a room. They begin a conversation — never a substitute for verified, completed work.",
      finalTitle: "Let the drawings begin the conversation.",
      finalSubtext: "Share what you have today. We'll take it from there.",
    },
    pages: {
      collections: ["Collections", "Made-to-order systems for complete interiors", "Every collection is a starting point. Dimensions, construction, material, hardware and finish are developed around the project."],
      solutions: ["Solutions", "One manufacturing partner across the project", "Different sectors ask different questions. Our workflow adapts while drawing control, sampling and quality checks stay consistent."],
      projects: ["Projects", "Proof, not mood boards", "Only verified work belongs here. The launch preview explains our case-study standard while your real project photography is being prepared."],
      capabilities: ["Capabilities", "Detail is a delivery system", "A custom interior succeeds when design, material, production and installation information stay coordinated."],
      company: ["Company", "A small name for work that shapes an entire room", "MLWK began as a mark on architectural drawings. Today it stands for a manufacturing team bringing more than 500 completed custom projects into thoughtful global partnerships."],
      resources: ["Resources", "Useful before the first quotation", "Catalogues, finish references and technical guidance will be published as each document is verified."],
      privacy: ["Privacy", "How enquiry information is handled", "A concise launch-stage privacy notice for project enquiries and uploaded drawings."],
      terms: ["Terms", "Website and enquiry terms", "Basic terms for using MLWK content and requesting project information."],
    },
    capabilitySteps: [
      ["01", "Review", "We review drawings, scope, destination and target programme."],
      ["02", "Develop", "Shop drawings, construction details and interfaces are coordinated."],
      ["03", "Sample", "Materials, finishes and critical details are confirmed before production."],
      ["04", "Manufacture", "Production follows the approved package with staged quality checks."],
      ["05", "Pack", "Components are protected, labeled and organized by area or room."],
      ["06", "Support", "Installation drawings, numbering and remote guidance support the local team."],
    ],
    quote: {
      eyebrow: "Project enquiry",
      title: "Send your drawings",
      intro: "Share what you know today. PDF, DWG, DXF, ZIP, JPG and PNG files are accepted, up to five files and 100 MB total.",
      fields: { name: "Name", company: "Company", email: "Work email", whatsapp: "WhatsApp / phone", country: "Country", projectType: "Project type", location: "Project location", scope: "Required scope", quantity: "Estimated quantity", budget: "Budget range", delivery: "Target delivery", message: "Project notes", files: "Drawings and references", consent: "I agree that MLWK may use this information to respond to my project enquiry.", submit: "Submit project", uploading: "Sending project…", success: "Your project has been received.", successText: "Our team will review the scope and reply using the contact details provided.", error: "The enquiry could not be sent. Please try again or use WhatsApp." },
    },
    legal: {
      privacy: ["We collect the contact and project information that you submit through the enquiry form.", "Uploaded files are used only to review and respond to the relevant project request.", "We do not sell enquiry information. Service providers may process data only to operate hosting, storage, security and email delivery.", "You may request access, correction or deletion by contacting MLWK through the published business email."],
      terms: ["Website imagery labeled as a design direction is conceptual and is not presented as completed client work.", "Specifications, quotations, schedules and availability are confirmed only in a written project proposal.", "Drawings and files remain the property of their respective owners and are reviewed only for the requested project.", "MLWK names, text and original media may not be republished without permission."],
    },
  },
  zh: {
    nav: { collections: "产品系统", solutions: "项目方案", projects: "项目案例", capabilities: "交付能力", company: "关于我们", quote: "上传图纸询价" },
    common: { explore: "查看", viewAll: "查看全部", learnMore: "了解更多", concept: "设计方向", back: "返回", openMenu: "打开菜单", closeMenu: "关闭菜单", language: "语言" },
    home: {
      badge: "为建筑而生的定制木作",
      title: "为值得被记住的空间而作",
      intro: "从第一笔线稿到最后一道木纹，我们让柜体、墙板与门成为建筑的一部分，并为跨境交付做好每一个细节。",
      proofValue: "500+",
      proofLabel: "制造团队共同完成的定制空间",
      collectionsEyebrow: "让一种材质语言贯穿整个空间",
      collectionsTitle: "当建筑开始拥有人的温度",
      collectionsText: "厨房、衣柜、门与墙板不再彼此分离，而是被深化为一个连续、克制而完整的室内。",
      processEyebrow: "从第一根线，到最终落地",
      processTitle: "以安静的精度，解决复杂定制",
      processText: "图纸、样品、编号和包装，每一个步骤都在减少下一步的不确定，让独特设计拥有清晰的制造与安装路径。",
      directionEyebrow: "材质叙事",
      directionTitle: "不是风格目录，而是属于项目的空间语言",
      directionText: "这些概念影像探索氛围、比例与材质的连续性。它们是对话的起点，不会被包装成已经完成的项目。",
      finalTitle: "让图纸，成为我们的第一次对话。",
      finalSubtext: "分享你目前已有的资料，我们来接手后续。",
    },
    pages: {
      collections: ["产品系统", "面向完整空间的定制木作", "每个产品系列都是起点，尺寸、结构、材料、五金与饰面都围绕项目深化。"],
      solutions: ["项目方案", "一个制造伙伴，贯穿整个项目", "不同业态有不同重点，但图纸控制、样品确认与质量检查始终一致。"],
      projects: ["项目案例", "只展示可核验的成果", "这里仅发布真实项目。首发预览先说明案例标准，待你的项目照片整理完成后逐步上线。"],
      capabilities: ["交付能力", "细节本身就是交付系统", "设计、材料、生产与安装信息始终协同，定制项目才能顺利落地。"],
      company: ["关于 MLWK", "一个很短的名字，关乎整个空间", "MLWK 最初只是建筑图纸上的一个标记。今天，它代表一支完成过 500 多个定制项目、正在认真走向全球合作的制造团队。"],
      resources: ["资料中心", "在首次报价前就有用的信息", "产品目录、饰面参考与技术资料将在核实后逐步发布。"],
      privacy: ["隐私政策", "我们如何处理询盘信息", "适用于项目询盘和上传图纸的简明隐私说明。"],
      terms: ["使用条款", "网站与询价条款", "使用 MLWK 内容和提交项目资料的基本条款。"],
    },
    capabilitySteps: [
      ["01", "评估", "审核图纸、范围、目的地与计划时间。"],
      ["02", "深化", "协调生产图、结构节点与专业接口。"],
      ["03", "打样", "生产前确认材料、饰面和关键节点。"],
      ["04", "制造", "依据批准资料生产，并执行分阶段质检。"],
      ["05", "包装", "按区域或房间保护、编号并组织部件。"],
      ["06", "支持", "通过安装图、编号与远程指导支持当地团队。"],
    ],
    quote: {
      eyebrow: "项目询盘",
      title: "上传你的图纸",
      intro: "先提交当前已有的信息。支持 PDF、DWG、DXF、ZIP、JPG 和 PNG，最多 5 个文件，总计不超过 100 MB。",
      fields: { name: "姓名", company: "公司", email: "工作邮箱", whatsapp: "WhatsApp / 电话", country: "国家", projectType: "项目类型", location: "项目地点", scope: "需求范围", quantity: "预计数量", budget: "预算区间", delivery: "目标交期", message: "项目说明", files: "图纸与参考资料", consent: "我同意 MLWK 使用这些信息回复本次项目询盘。", submit: "提交项目", uploading: "正在发送…", success: "项目资料已收到。", successText: "团队将审核范围，并通过你填写的联系方式回复。", error: "发送失败，请重试或通过 WhatsApp 联系。" },
    },
    legal: {
      privacy: ["我们收集你通过询盘表单提交的联系方式和项目信息。", "上传文件仅用于审核并回复对应的项目需求。", "我们不会出售询盘信息；托管、存储、安全与邮件服务商仅为运行网站处理必要数据。", "你可以通过公开的业务邮箱申请访问、更正或删除信息。"],
      terms: ["标注为“设计方向”的网站视觉属于概念内容，不代表已完工客户项目。", "规格、报价、进度与供货情况仅以书面项目方案为准。", "图纸和文件的权利归各自所有者，仅用于所请求的项目审核。", "未经许可，不得转载 MLWK 名称、文字与原创媒体。"],
    },
  },
  ar: {
    nav: { collections: "المجموعات", solutions: "الحلول", projects: "المشاريع", capabilities: "القدرات", company: "الشركة", quote: "أرسل مخططاتك" },
    common: { explore: "استكشف", viewAll: "عرض الكل", learnMore: "اعرف المزيد", concept: "اتجاه تصميمي", back: "عودة", openMenu: "فتح القائمة", closeMenu: "إغلاق القائمة", language: "اللغة" },
    home: {
      badge: "أعمال خشبية صُممت لتنتمي",
      title: "مصنوعة للمساحات التي تبقى في الذاكرة",
      intro: "من أول خط بالقلم إلى آخر تطابق في عروق الخشب، تصوغ MLWK الخزائن والأعمال الخشبية المعمارية للمنازل والفنادق والمساحات المصممة لتدوم.",
      proofValue: "+500",
      proofLabel: "مساحات مخصصة أنجزها فريق التصنيع",
      collectionsEyebrow: "لغة مادية واحدة تمتد عبر المكان",
      collectionsTitle: "حين تصبح العمارة أكثر شخصية",
      collectionsText: "نطوّر المطابخ والخزائن والأبواب والجدران كمساحة داخلية متصلة، لا كمجموعة من العناصر المنفصلة.",
      processEyebrow: "من الخط الأول إلى الغرفة الأخيرة",
      processTitle: "أعمال معقدة تُحل بدقة هادئة",
      processText: "كل مخطط وعينة وملصق يدفع المشروع إلى الأمام، ويحوّل التصميم المتفرد إلى مسار واضح للتصنيع والتركيب.",
      directionEyebrow: "حكايات المواد",
      directionTitle: "ليست قائمة أنماط، بل لغة خاصة بمشروعك",
      directionText: "تستكشف هذه الصور التصورية الجو والنسب واستمرارية المواد. إنها بداية للحوار وليست بديلاً عن مشروع منفذ وموثق.",
      finalTitle: "دع المخططات تبدأ الحوار.",
      finalSubtext: "شارك ما لديك اليوم، نحن نتولى الباقي.",
    },
    pages: {
      collections: ["المجموعات", "أنظمة حسب الطلب لمساحات متكاملة", "كل مجموعة نقطة بداية، ونطور الأبعاد والبناء والمواد والحديد والتشطيب حسب المشروع."],
      solutions: ["الحلول", "شريك تصنيع واحد عبر المشروع", "تختلف الأسئلة حسب القطاع بينما تبقى دقة الرسومات والعينات وفحوص الجودة ثابتة."],
      projects: ["المشاريع", "أدلة حقيقية لا لوحات مزاجية", "لا نعرض هنا إلا أعمالاً موثقة. يوضح العرض الأول معيار دراسة الحالة حتى تجهز صور المشاريع الحقيقية."],
      capabilities: ["القدرات", "التفاصيل هي نظام التسليم", "ينجح العمل المخصص عندما تتناغم معلومات التصميم والمواد والإنتاج والتركيب."],
      company: ["الشركة", "اسم صغير لعمل يصوغ الغرفة بأكملها", "بدأت MLWK كعلامة على المخططات المعمارية. واليوم تمثل فريقاً صناعياً يحمل خبرة أكثر من 500 مشروع مخصص إلى شراكات عالمية مدروسة."],
      resources: ["الموارد", "معلومات مفيدة قبل أول عرض سعر", "ستنشر الكتالوجات ومراجع التشطيب والإرشادات الفنية بعد التحقق منها."],
      privacy: ["الخصوصية", "كيفية التعامل مع بيانات الاستفسار", "إشعار موجز لبيانات المشاريع والمخططات المرفوعة."],
      terms: ["الشروط", "شروط الموقع والاستفسار", "الشروط الأساسية لاستخدام محتوى MLWK وطلب معلومات المشروع."],
    },
    capabilitySteps: [
      ["01", "المراجعة", "نراجع المخططات والنطاق والوجهة والبرنامج المطلوب."],
      ["02", "التطوير", "ننسق الرسومات التنفيذية والتفاصيل والواجهات."],
      ["03", "العينة", "نعتمد المواد والتشطيبات والتفاصيل الحرجة قبل الإنتاج."],
      ["04", "التصنيع", "يتم الإنتاج وفق الحزمة المعتمدة مع فحوص جودة مرحلية."],
      ["05", "التغليف", "تُحمى القطع وترقم وتنظم حسب المنطقة أو الغرفة."],
      ["06", "الدعم", "تدعم الرسومات والترقيم والإرشاد عن بعد فريق التركيب المحلي."],
    ],
    quote: {
      eyebrow: "استفسار مشروع",
      title: "أرسل مخططاتك",
      intro: "شارك ما يتوفر لديك الآن. نقبل PDF وDWG وDXF وZIP وJPG وPNG، حتى خمسة ملفات وبإجمالي 100 ميغابايت.",
      fields: { name: "الاسم", company: "الشركة", email: "بريد العمل", whatsapp: "واتساب / هاتف", country: "الدولة", projectType: "نوع المشروع", location: "موقع المشروع", scope: "النطاق المطلوب", quantity: "الكمية التقديرية", budget: "نطاق الميزانية", delivery: "موعد التسليم", message: "ملاحظات المشروع", files: "المخططات والمراجع", consent: "أوافق على استخدام MLWK لهذه المعلومات للرد على استفساري.", submit: "إرسال المشروع", uploading: "جارٍ الإرسال…", success: "تم استلام مشروعك.", successText: "سيراجع الفريق النطاق ويتواصل عبر البيانات المقدمة.", error: "تعذر الإرسال. حاول مرة أخرى أو استخدم واتساب." },
    },
    legal: {
      privacy: ["نجمع بيانات الاتصال والمشروع التي ترسلها عبر نموذج الاستفسار.", "تستخدم الملفات المرفوعة فقط لمراجعة الطلب والرد عليه.", "لا نبيع بيانات الاستفسارات، وقد يعالجها مقدمو الاستضافة والتخزين والأمان والبريد لتشغيل الخدمة.", "يمكنك طلب الوصول أو التصحيح أو الحذف عبر بريد العمل المنشور."],
      terms: ["الصور الموسومة كاتجاه تصميمي هي تصورات وليست أعمال عملاء منفذة.", "لا تُعتمد المواصفات والأسعار والجداول والتوفر إلا في عرض مشروع مكتوب.", "تظل حقوق المخططات والملفات لأصحابها وتراجع فقط للمشروع المطلوب.", "لا يجوز إعادة نشر اسم MLWK أو نصوصه أو وسائطه الأصلية دون إذن."],
    },
  },
  de: {
    nav: { collections: "Kollektionen", solutions: "Lösungen", projects: "Projekte", capabilities: "Kompetenzen", company: "Unternehmen", quote: "Pläne senden" },
    common: { explore: "Entdecken", viewAll: "Alle ansehen", learnMore: "Mehr erfahren", concept: "Designrichtung", back: "Zurück", openMenu: "Menü öffnen", closeMenu: "Menü schließen", language: "Sprache" },
    home: {
      badge: "Millwork, das zum Raum gehört",
      title: "Für Räume, die in Erinnerung bleiben",
      intro: "Von der ersten Bleistiftlinie bis zum letzten Furnierbild formt MLWK Möbel und architektonischen Innenausbau für Häuser, Hotels und Räume von Dauer.",
      proofValue: "500+",
      proofLabel: "Individuelle Räume unseres Fertigungsteams",
      collectionsEyebrow: "Eine Materialsprache für den ganzen Raum",
      collectionsTitle: "Wo Architektur persönlich wird",
      collectionsText: "Küchen, Schränke, Türen und Paneelräume entstehen als durchgängiges Interieur statt als Sammlung einzelner Objekte.",
      processEyebrow: "Von der ersten Linie bis zum fertigen Raum",
      processTitle: "Komplexität, mit stiller Präzision gelöst",
      processText: "Jeder Plan, jedes Muster und jede Kennzeichnung bringt das Projekt voran und schafft einen klaren Weg zu Fertigung und Montage.",
      directionEyebrow: "Materialgeschichten",
      directionTitle: "Kein Stilkatalog. Eine Sprache für Ihr Projekt.",
      directionText: "Diese Konzeptstudien erkunden Atmosphäre, Proportion und Materialkontinuität. Sie eröffnen den Dialog und ersetzen nie belegte Referenzen.",
      finalTitle: "Lassen Sie die Pläne das Gespräch beginnen.",
      finalSubtext: "Teilen Sie den aktuellen Stand. Wir übernehmen das Weitere.",
    },
    pages: {
      collections: ["Kollektionen", "Maßgefertigte Systeme für komplette Innenräume", "Abmessungen, Konstruktion, Materialien, Beschläge und Oberflächen werden projektbezogen entwickelt."],
      solutions: ["Lösungen", "Ein Fertigungspartner für das gesamte Projekt", "Die Anforderungen ändern sich je nach Sektor; Planprüfung, Bemusterung und Qualitätskontrolle bleiben konstant."],
      projects: ["Projekte", "Belege statt Moodboards", "Hier erscheint nur verifizierte Arbeit. Die Vorschau erklärt den Fallstudienstandard, während reale Bilder vorbereitet werden."],
      capabilities: ["Kompetenzen", "Details bilden das Liefersystem", "Individueller Innenausbau gelingt, wenn Entwurf, Material, Fertigung und Montage koordiniert bleiben."],
      company: ["Unternehmen", "Ein kurzer Name für Arbeit, die ganze Räume prägt", "MLWK begann als Kürzel auf Architekturplänen. Heute steht es für ein Fertigungsteam, das die Erfahrung aus über 500 Sonderprojekten in sorgfältige globale Partnerschaften einbringt."],
      resources: ["Ressourcen", "Nützlich vor dem ersten Angebot", "Kataloge, Oberflächenreferenzen und technische Hinweise werden nach Prüfung veröffentlicht."],
      privacy: ["Datenschutz", "Umgang mit Anfrageinformationen", "Kurzer Datenschutzhinweis für Projektanfragen und hochgeladene Pläne."],
      terms: ["Bedingungen", "Website- und Anfragebedingungen", "Grundbedingungen für die Nutzung von MLWK-Inhalten und Projektanfragen."],
    },
    capabilitySteps: [
      ["01", "Prüfen", "Wir prüfen Pläne, Umfang, Zielort und Terminplan."],
      ["02", "Entwickeln", "Werkpläne, Konstruktion und Schnittstellen werden koordiniert."],
      ["03", "Bemustern", "Materialien, Oberflächen und kritische Details werden bestätigt."],
      ["04", "Fertigen", "Produktion nach Freigabe mit gestuften Qualitätskontrollen."],
      ["05", "Verpacken", "Bauteile werden geschützt, beschriftet und nach Raum organisiert."],
      ["06", "Unterstützen", "Montagepläne, Nummerierung und Fernberatung helfen dem lokalen Team."],
    ],
    quote: {
      eyebrow: "Projektanfrage",
      title: "Senden Sie Ihre Pläne",
      intro: "Teilen Sie den aktuellen Stand. PDF, DWG, DXF, ZIP, JPG und PNG, maximal fünf Dateien und 100 MB gesamt.",
      fields: { name: "Name", company: "Unternehmen", email: "Geschäftliche E-Mail", whatsapp: "WhatsApp / Telefon", country: "Land", projectType: "Projekttyp", location: "Projektort", scope: "Leistungsumfang", quantity: "Geschätzte Menge", budget: "Budgetrahmen", delivery: "Zieltermin", message: "Projekthinweise", files: "Pläne und Referenzen", consent: "Ich stimme zu, dass MLWK diese Angaben zur Bearbeitung der Anfrage verwendet.", submit: "Projekt senden", uploading: "Projekt wird gesendet…", success: "Ihr Projekt wurde empfangen.", successText: "Unser Team prüft den Umfang und antwortet über die angegebenen Kontaktdaten.", error: "Die Anfrage konnte nicht gesendet werden. Bitte erneut versuchen oder WhatsApp nutzen." },
    },
    legal: {
      privacy: ["Wir erfassen die Kontakt- und Projektangaben, die Sie über das Anfrageformular senden.", "Hochgeladene Dateien werden nur zur Prüfung und Beantwortung der jeweiligen Anfrage verwendet.", "Wir verkaufen keine Anfragedaten. Dienstleister verarbeiten Daten nur für Hosting, Speicher, Sicherheit und E-Mail.", "Zugriff, Berichtigung oder Löschung können über die veröffentlichte Geschäftsadresse angefragt werden."],
      terms: ["Als Designrichtung gekennzeichnete Bilder sind konzeptionell und keine realisierten Kundenprojekte.", "Spezifikationen, Angebote, Termine und Verfügbarkeit gelten erst mit einem schriftlichen Projektangebot.", "Zeichnungen und Dateien bleiben Eigentum der jeweiligen Rechteinhaber.", "MLWK-Namen, Texte und Originalmedien dürfen nicht ohne Erlaubnis veröffentlicht werden."],
    },
  },
  fr: {
    nav: { collections: "Collections", solutions: "Solutions", projects: "Projets", capabilities: "Savoir-faire", company: "Entreprise", quote: "Envoyer vos plans" },
    common: { explore: "Explorer", viewAll: "Tout voir", learnMore: "En savoir plus", concept: "Direction créative", back: "Retour", openMenu: "Ouvrir le menu", closeMenu: "Fermer le menu", language: "Langue" },
    home: {
      badge: "Une menuiserie faite pour appartenir au lieu",
      title: "Pour les pièces dont on se souvient",
      intro: "Du premier trait de crayon au dernier raccord de veinage, MLWK façonne mobilier et menuiserie architecturale pour des maisons, hôtels et lieux conçus pour durer.",
      proofValue: "500+",
      proofLabel: "Intérieurs sur mesure façonnés par notre équipe",
      collectionsEyebrow: "Un même langage de matière dans toute la pièce",
      collectionsTitle: "Quand l'architecture devient personnelle",
      collectionsText: "Cuisines, dressings, portes et panneaux sont développés comme un intérieur continu, et non comme une série d'objets séparés.",
      processEyebrow: "Du premier trait à la pièce achevée",
      processTitle: "La complexité résolue avec une précision discrète",
      processText: "Chaque plan, échantillon et repère fait avancer le projet et transforme un dessin singulier en chemin clair vers la fabrication et la pose.",
      directionEyebrow: "Récits de matières",
      directionTitle: "Pas un catalogue de styles. Un langage pour votre projet.",
      directionText: "Ces études conceptuelles explorent l'atmosphère, les proportions et la continuité des matières. Elles ouvrent le dialogue sans remplacer les réalisations vérifiées.",
      finalTitle: "Que les plans ouvrent la conversation.",
      finalSubtext: "Partagez ce que vous avez aujourd'hui. Nous prenons le relais.",
    },
    pages: {
      collections: ["Collections", "Des systèmes sur mesure pour des intérieurs complets", "Dimensions, construction, matériaux, quincaillerie et finitions sont développés autour du projet."],
      solutions: ["Solutions", "Un partenaire de fabrication pour tout le projet", "Les priorités changent selon le secteur ; le contrôle des plans, les échantillons et la qualité restent constants."],
      projects: ["Projets", "Des preuves, pas des planches d'ambiance", "Seules les réalisations vérifiées figurent ici. L'aperçu présente notre standard en attendant vos photographies réelles."],
      capabilities: ["Savoir-faire", "Le détail est un système de livraison", "Le sur-mesure réussit lorsque design, matériaux, fabrication et pose restent coordonnés."],
      company: ["Entreprise", "Un nom court pour un travail qui façonne toute la pièce", "MLWK était d'abord une annotation sur les plans d'architecture. Aujourd'hui, ce nom porte l'expérience de plus de 500 projets sur mesure vers des partenariats internationaux choisis."],
      resources: ["Ressources", "Utile avant le premier devis", "Catalogues, références de finitions et guides techniques seront publiés après vérification."],
      privacy: ["Confidentialité", "Traitement des informations de demande", "Une notice concise pour les demandes de projet et les plans téléchargés."],
      terms: ["Conditions", "Conditions du site et des demandes", "Conditions de base pour utiliser le contenu MLWK et demander des informations."],
    },
    capabilitySteps: [
      ["01", "Analyser", "Nous examinons plans, périmètre, destination et calendrier."],
      ["02", "Développer", "Plans d'atelier, détails et interfaces sont coordonnés."],
      ["03", "Échantillonner", "Matériaux, finitions et détails critiques sont validés."],
      ["04", "Fabriquer", "La production suit le dossier approuvé avec des contrôles par étapes."],
      ["05", "Emballer", "Les éléments sont protégés, repérés et organisés par zone."],
      ["06", "Accompagner", "Plans de pose, repérage et assistance à distance soutiennent l'équipe locale."],
    ],
    quote: {
      eyebrow: "Demande de projet",
      title: "Envoyez vos plans",
      intro: "Partagez les éléments disponibles. PDF, DWG, DXF, ZIP, JPG et PNG, cinq fichiers maximum et 100 Mo au total.",
      fields: { name: "Nom", company: "Entreprise", email: "E-mail professionnel", whatsapp: "WhatsApp / téléphone", country: "Pays", projectType: "Type de projet", location: "Lieu du projet", scope: "Périmètre demandé", quantity: "Quantité estimée", budget: "Fourchette budgétaire", delivery: "Livraison souhaitée", message: "Notes du projet", files: "Plans et références", consent: "J'accepte que MLWK utilise ces informations pour répondre à ma demande.", submit: "Envoyer le projet", uploading: "Envoi en cours…", success: "Votre projet a bien été reçu.", successText: "Notre équipe examinera le périmètre et répondra avec les coordonnées fournies.", error: "La demande n'a pas pu être envoyée. Réessayez ou utilisez WhatsApp." },
    },
    legal: {
      privacy: ["Nous collectons les coordonnées et informations de projet envoyées via le formulaire.", "Les fichiers servent uniquement à examiner et répondre à la demande concernée.", "Nous ne vendons pas les données. Des prestataires peuvent les traiter pour l'hébergement, le stockage, la sécurité et l'e-mail.", "Vous pouvez demander accès, correction ou suppression via l'adresse professionnelle publiée."],
      terms: ["Les images signalées comme direction créative sont conceptuelles et ne représentent pas un projet client réalisé.", "Spécifications, devis, délais et disponibilités ne sont confirmés que par une proposition écrite.", "Les plans et fichiers restent la propriété de leurs détenteurs respectifs.", "Les noms, textes et médias originaux MLWK ne peuvent être republiés sans autorisation."],
    },
  },
} as const;

export function isLocale(value: string | undefined): value is Locale {
  return locales.includes(value as Locale);
}

export function getCopy(locale: Locale) {
  return copy[locale];
}
